import "@apexui/tokens/css";
import "@apexui/web-components/components/apex-alert.js";
import "@apexui/web-components/components/apex-app-bar.js";
import "@apexui/web-components/components/apex-badge.js";
import "@apexui/web-components/components/apex-button.js";
import "@apexui/web-components/components/apex-calendar.js";
import "@apexui/web-components/components/apex-card.js";
import "@apexui/web-components/components/apex-chart.js";
import "@apexui/web-components/components/apex-data-table.js";
import "@apexui/web-components/components/apex-progress.js";
import "@apexui/web-components/components/apex-snackbar.js";
import "@apexui/web-components/components/apex-stack.js";
import "@apexui/web-components/components/apex-switch.js";
import "@apexui/web-components/components/apex-text-field.js";
import "@apexui/web-components/components/apex-typography.js";
import "./styles.css";
const chart = document.querySelector("#support-chart") as HTMLElement & { data?: Array<{ label: string; value: number }> };
chart.data = [{ "label": "Tokens", "value": 92 }, { "label": "Components", "value": 84 }, { "label": "Routes", "value": 73 }];
const table = document.querySelector("#support-table") as HTMLElement & { columns?: Array<{ key: string; header: string }>; rows?: Array<Record<string, string>> };
table.columns = [{ "key": "area", "header": "Area" }, { "key": "owner", "header": "Owner" }, { "key": "status", "header": "Status" }];
table.rows = [{ "area": "Tokens", "owner": "Platform", "status": "Live" }, { "area": "Components", "owner": "Design system", "status": "Beta" }, { "area": "Docs", "owner": "DX", "status": "Linked" }];
document.querySelector("#primary-action")?.addEventListener("click", () => document.querySelector("#snackbar")?.setAttribute("open", "true"));
